package seleniumTestSuite;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class InserimentoProdottoTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
		 js = (JavascriptExecutor) driver;
			vars = new HashMap<String, Object>();
			System.setProperty("webdriver.chrome.driver",
					"C:\\Users\\franc\\Desktop\\Selenium\\chromedriver_win32\\chromedriver.exe");
			//System.setProperty("webdriver.chrome.driver","C:\\Users\\luigi\\Documents\\chromedriver_win32\\chromedriver.exe");
			//System.setProperty("webdriver.chrome.driver","C:\\Users\\ricca\\Downloads\\chromedriver_win32\\chromedriver.exe");
			driver = new ChromeDriver();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void inserimentoProdotto211() {
    driver.get("http://localhost:8080/DressMe/loginPersonale.jsp");
    driver.manage().window().setSize(new Dimension(1057, 803));
    driver.findElement(By.id("username")).click();
    driver.findElement(By.id("username")).sendKeys("prodotti@gmail.com");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("AdminAdmin");
    driver.findElement(By.id("login-submit")).click();
    driver.findElement(By.cssSelector("input:nth-child(31)")).click();
  }
  @Test
  public void inserimentoProdotto212() {
    driver.get("http://localhost:8080/DressMe/loginPersonale.jsp");
    driver.manage().window().setSize(new Dimension(1075, 816));
    driver.findElement(By.id("username")).click();
    driver.findElement(By.id("username")).sendKeys("prodotti@gmail.com");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("AdminAdmin");
    driver.findElement(By.id("login-submit")).click();
    driver.findElement(By.id("codiceVestito")).click();
    driver.findElement(By.id("codiceVestito")).sendKeys("AAA");
    driver.findElement(By.id("quantitaVestito")).click();
    driver.findElement(By.id("quantitaVestito")).click();
    driver.findElement(By.id("quantitaVestito")).sendKeys("15");
    driver.findElement(By.id("titolo")).click();
    driver.findElement(By.id("titolo")).sendKeys("Maglia blu");
    driver.findElement(By.id("descrizione")).click();
    driver.findElement(By.id("descrizione")).sendKeys("Maglia in cotone blu");
    driver.findElement(By.id("prezzo")).click();
    driver.findElement(By.id("prezzo")).sendKeys("14");
    driver.findElement(By.cssSelector("input:nth-child(31)")).click();
    assertThat(driver.switchTo().alert().getText(), is("Il codice che hai inserito non è valido"));
  }
  @Test
  public void inserimentoProdotto213() {
    driver.get("http://localhost:8080/DressMe/loginPersonale.jsp");
    driver.manage().window().setSize(new Dimension(1075, 816));
    driver.findElement(By.id("username")).click();
    driver.findElement(By.id("username")).sendKeys("prodotti@gmail.com");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("AdminAdmin");
    driver.findElement(By.id("login-submit")).click();
    driver.findElement(By.id("codiceVestito")).click();
    driver.findElement(By.id("codiceVestito")).sendKeys("MG002");
    driver.findElement(By.id("quantitaVestito")).click();
    driver.findElement(By.id("quantitaVestito")).sendKeys("15");
    driver.findElement(By.id("titolo")).click();
    driver.findElement(By.id("titolo")).sendKeys("Maglia blu");
    driver.findElement(By.id("descrizione")).click();
    driver.findElement(By.id("descrizione")).sendKeys("Maglia in cotone blu");
    driver.findElement(By.id("prezzo")).click();
    driver.findElement(By.id("prezzo")).sendKeys("0");
    driver.findElement(By.cssSelector("input:nth-child(31)")).click();
    assertThat(driver.switchTo().alert().getText(), is("Il codice che hai inserito non è valido"));
  }
  @Test
  public void inserimentoProdotto215() {
    driver.get("http://localhost:8080/DressMe/loginPersonale.jsp");
    driver.manage().window().setSize(new Dimension(1075, 816));
    driver.findElement(By.id("username")).click();
    driver.findElement(By.id("username")).sendKeys("prodotti@gmail.com");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("AdminAdmin");
    driver.findElement(By.id("login-submit")).click();
    driver.findElement(By.id("codiceVestito")).click();
    driver.findElement(By.id("codiceVestito")).sendKeys("MG515");
    driver.findElement(By.id("quantitaVestito")).click();
    driver.findElement(By.id("quantitaVestito")).sendKeys("15");
    driver.findElement(By.id("titolo")).click();
    driver.findElement(By.id("titolo")).sendKeys("Maglia blu");
    driver.findElement(By.id("descrizione")).click();
    driver.findElement(By.id("descrizione")).sendKeys("Maglia in cotone blu");
    driver.findElement(By.id("prezzo")).click();
    driver.findElement(By.id("prezzo")).sendKeys("14");
    driver.findElement(By.cssSelector("input:nth-child(31)")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("p"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void inserimentoProdotto214() {
    driver.get("http://localhost:8080/DressMe/loginPersonale.jsp");
    driver.manage().window().setSize(new Dimension(1076, 816));
    driver.findElement(By.id("username")).click();
    driver.findElement(By.id("username")).sendKeys("prodotti@gmail.com");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("AdminAdmin");
    driver.findElement(By.id("login-submit")).click();
    driver.findElement(By.id("codiceVestito")).click();
    driver.findElement(By.id("codiceVestito")).sendKeys("MG002");
    driver.findElement(By.id("quantitaVestito")).click();
    driver.findElement(By.id("quantitaVestito")).sendKeys("15");
    driver.findElement(By.id("titolo")).click();
    driver.findElement(By.id("titolo")).sendKeys("Maglia blu");
    driver.findElement(By.id("descrizione")).click();
    driver.findElement(By.id("descrizione")).sendKeys("Maglia in cotone blu");
    driver.findElement(By.id("prezzo")).click();
    driver.findElement(By.id("prezzo")).sendKeys("14");
    driver.findElement(By.cssSelector("input:nth-child(31)")).click();
    assertThat(driver.switchTo().alert().getText(), is("Il codice che hai inserito non è valido"));
  }
}
