package seleniumTestSuite;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class InserimentoPersonaleTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
		 js = (JavascriptExecutor) driver;
			vars = new HashMap<String, Object>();
			System.setProperty("webdriver.chrome.driver",
					"C:\\Users\\franc\\Desktop\\Selenium\\chromedriver_win32\\chromedriver.exe");
			driver = new ChromeDriver();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void inserimentoPersonale141() {
    driver.get("http://localhost:8080/DressMe/loginPersonale.jsp");
    driver.manage().window().setSize(new Dimension(813, 816));
    driver.findElement(By.id("username")).click();
    driver.findElement(By.id("username")).sendKeys("admin@gmail.com");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("AdminAdmin");
    driver.findElement(By.id("login-submit")).click();
    driver.findElement(By.cssSelector("input:nth-child(23)")).click();
  }
  @Test
  public void inserimentoPersonale142() {
    driver.get("http://localhost:8080/DressMe/loginPersonale.jsp");
    driver.manage().window().setSize(new Dimension(813, 816));
    driver.findElement(By.id("username")).click();
    driver.findElement(By.id("username")).sendKeys("admin@gmail.com");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("AdminAdmin");
    driver.findElement(By.id("login-submit")).click();
    driver.findElement(By.id("nome")).click();
    driver.findElement(By.id("nome")).sendKeys("Luca");
    driver.findElement(By.id("cognome")).click();
    driver.findElement(By.id("cognome")).sendKeys("Abete");
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("lucaabete.com");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("AdminAdmin");
    driver.findElement(By.cssSelector("input:nth-child(23)")).click();
  }
  @Test
  public void inserimentoPersonale143() {
    driver.get("http://localhost:8080/DressMe/loginPersonale.jsp");
    driver.manage().window().setSize(new Dimension(815, 816));
    driver.findElement(By.id("username")).click();
    driver.findElement(By.id("username")).sendKeys("admin@gmail.com");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("AdminAdmin");
    driver.findElement(By.id("login-submit")).click();
    driver.findElement(By.id("nome")).click();
    driver.findElement(By.id("nome")).sendKeys("Luca");
    driver.findElement(By.id("cognome")).click();
    driver.findElement(By.id("cognome")).sendKeys("Abete");
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("lucaabete@gmail.com");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("aaaa");
    driver.findElement(By.id("ruolo")).click();
    {
      WebElement dropdown = driver.findElement(By.id("ruolo"));
      dropdown.findElement(By.xpath("//option[. = 'Gestore prodotti']")).click();
    }
    driver.findElement(By.cssSelector("input:nth-child(23)")).click();
    assertThat(driver.switchTo().alert().getText(), is("La password che hai inserito non è valida"));
  }
  @Test
  public void inserimentoPersonale144() {
    driver.get("http://localhost:8080/DressMe/loginPersonale.jsp");
    driver.manage().window().setSize(new Dimension(1054, 801));
    driver.findElement(By.id("username")).click();
    driver.findElement(By.id("username")).sendKeys("admin@gmail.com");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("AdminAdmin");
    driver.findElement(By.id("login-submit")).click();
    driver.findElement(By.id("nome")).click();
    driver.findElement(By.id("nome")).sendKeys("Luca");
    driver.findElement(By.id("cognome")).click();
    driver.findElement(By.id("cognome")).sendKeys("Abete");
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("lucaabete@gmail.com");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("ABCD1234");
    driver.findElement(By.id("ruolo")).click();
    {
      WebElement dropdown = driver.findElement(By.id("ruolo"));
      dropdown.findElement(By.xpath("//option[. = 'Gestore prodotti']")).click();
    }
    driver.findElement(By.cssSelector("input:nth-child(23)")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("p"));
      assert(elements.size() > 0);
    }
  }
}
