package seleniumTestSuite;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class LoginClienteTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
		 js = (JavascriptExecutor) driver;
			vars = new HashMap<String, Object>();
			System.setProperty("webdriver.chrome.driver",
					"C:\\Users\\franc\\Desktop\\Selenium\\chromedriver_win32\\chromedriver.exe");
			driver = new ChromeDriver();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void loginCliente121() {
    driver.get("http://localhost:8080/DressMe/");
    driver.manage().window().setSize(new Dimension(800, 816));
    driver.findElement(By.linkText("Login")).click();
    driver.findElement(By.id("login-submit")).click();
  }
  @Test
  public void loginCliente122() {
    driver.get("http://localhost:8080/DressMe/");
    driver.manage().window().setSize(new Dimension(800, 816));
    driver.findElement(By.linkText("Login")).click();
    driver.findElement(By.id("login-username")).click();
    driver.findElement(By.id("login-username")).sendKeys("abcd");
    driver.findElement(By.id("login-password")).click();
    driver.findElement(By.id("login-password")).sendKeys("ABCD1234");
    driver.findElement(By.id("login-submit")).click();
    {
      List<WebElement> elements = driver.findElements(By.id("login-message"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void loginCliente123() {
    driver.get("http://localhost:8080/DressMe/");
    driver.manage().window().setSize(new Dimension(800, 816));
    driver.findElement(By.linkText("Login")).click();
    driver.findElement(By.id("login-username")).click();
    driver.findElement(By.id("login-username")).sendKeys("ciromertens@gmail.com");
    driver.findElement(By.id("login-password")).click();
    driver.findElement(By.id("login-password")).sendKeys("1");
    driver.findElement(By.id("login-submit")).click();
    {
      List<WebElement> elements = driver.findElements(By.id("login-message"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void loginCliente124() {
    driver.get("http://localhost:8080/DressMe/");
    driver.manage().window().setSize(new Dimension(800, 816));
    driver.findElement(By.linkText("Login")).click();
    driver.findElement(By.id("login-username")).click();
    driver.findElement(By.id("login-username")).sendKeys("ciromertens@gmail.com");
    driver.findElement(By.id("login-password")).click();
    driver.findElement(By.id("login-password")).sendKeys("ABCD1234");
    driver.findElement(By.id("login-submit")).click();
    assertThat(driver.getTitle(), is("Homepage | DressMe Cloth collection"));
  }
}
