package seleniumTestSuite;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class ModificaOrdineTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
		 js = (JavascriptExecutor) driver;
			vars = new HashMap<String, Object>();
			System.setProperty("webdriver.chrome.driver",
					"C:\\Users\\franc\\Desktop\\Selenium\\chromedriver_win32\\chromedriver.exe");
			//System.setProperty("webdriver.chrome.driver","C:\\Users\\luigi\\Documents\\chromedriver_win32\\chromedriver.exe");
			//System.setProperty("webdriver.chrome.driver","C:\\Users\\ricca\\Downloads\\chromedriver_win32\\chromedriver.exe");
			
			driver = new ChromeDriver();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void modificaOrdine412() {
    driver.get("http://localhost:8080/DressMe/loginPersonale.jsp");
    driver.manage().window().setSize(new Dimension(786, 817));
    driver.findElement(By.id("username")).click();
    driver.findElement(By.id("username")).sendKeys("ordini@gmail.com");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("AdminAdmin");
    driver.findElement(By.id("login-submit")).click();
    driver.findElement(By.cssSelector("tr:nth-child(4) #dettagli")).click();
    driver.findElement(By.id("cap")).click();
    driver.findElement(By.id("cap")).sendKeys("831");
    driver.findElement(By.id("prezzo")).click();
    driver.findElement(By.id("prezzo")).sendKeys("12");
    driver.findElement(By.cssSelector("input:nth-child(40)")).click();
    assertThat(driver.switchTo().alert().getText(), is("Il CAP che hai inserito non è valido"));
  }
  @Test
  public void modificaOrdine413() {
    driver.get("http://localhost:8080/DressMe/loginPersonale.jsp");
    driver.manage().window().setSize(new Dimension(786, 817));
    driver.findElement(By.id("username")).click();
    driver.findElement(By.id("username")).sendKeys("ordini@gmail.com");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("AdminAdmin");
    driver.findElement(By.id("login-submit")).click();
    driver.findElement(By.cssSelector("tr:nth-child(4) #dettagli")).click();
    driver.findElement(By.id("prezzo")).click();
    driver.findElement(By.id("prezzo")).sendKeys("12");
    driver.findElement(By.cssSelector("input:nth-child(40)")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("p"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void eliminaOrdine() {
    driver.get("http://localhost:8080/DressMe/loginPersonale.jsp");
    driver.manage().window().setSize(new Dimension(1062, 808));
    driver.findElement(By.id("username")).click();
    driver.findElement(By.id("username")).sendKeys("ordini@gmail.com");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("AdminAdmin");
    driver.findElement(By.id("login-submit")).click();
    driver.findElement(By.cssSelector("tr:nth-child(4) #elimina")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("p"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void testAggiungiAlCarrello() {
    driver.get("http://localhost:8080/DressMe/");
    driver.manage().window().setSize(new Dimension(1066, 808));
    driver.findElement(By.linkText("Login")).click();
    driver.findElement(By.id("login-username")).sendKeys("pp9@gmail.com");
    driver.findElement(By.id("login-password")).sendKeys("l123456");
    driver.findElement(By.id("login-username")).click();
    driver.findElement(By.id("login-username")).sendKeys("nessuno@gmail.com");
    driver.findElement(By.id("login-password")).click();
    driver.findElement(By.id("login-password")).sendKeys("AdminAdmin");
    driver.findElement(By.id("login-submit")).click();
    driver.findElement(By.linkText("Bambini")).click();
    driver.findElement(By.cssSelector(".vetrina-item:nth-child(2) > .button")).click();
    assertThat(driver.getTitle(), is("Carrello | DressMe Cloth collection"));
  }
  @Test
  public void testConfermaOrdine() {
    driver.get("http://localhost:8080/DressMe/loginPersonale.jsp");
    driver.manage().window().setSize(new Dimension(1058, 808));
    driver.findElement(By.id("username")).click();
    driver.findElement(By.id("username")).click();
    driver.findElement(By.id("username")).sendKeys("ordini@gmail.com");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("AdminAdmin");
    driver.findElement(By.id("login-submit")).click();
    driver.findElement(By.cssSelector("tr:nth-child(6) #conferma")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("p"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void testEliminaDalCarrello() {
    driver.get("http://localhost:8080/DressMe/");
    driver.manage().window().setSize(new Dimension(1070, 808));
    driver.findElement(By.linkText("Login")).click();
    driver.findElement(By.id("login-username")).sendKeys("pp9@gmail.com");
    driver.findElement(By.id("login-password")).sendKeys("l123456");
    driver.findElement(By.id("login-username")).click();
    driver.findElement(By.id("login-username")).sendKeys("ne");
    driver.findElement(By.id("login-username")).click();
    driver.findElement(By.id("login-username")).sendKeys("nessuno@gmail.com");
    driver.findElement(By.id("login-password")).click();
    driver.findElement(By.id("login-password")).sendKeys("AdminAdmin");
    driver.findElement(By.id("login-submit")).click();
    driver.findElement(By.linkText("Bambini")).click();
    driver.findElement(By.cssSelector(".vetrina-item:nth-child(1) > .button > b")).click();
    driver.findElement(By.cssSelector("tr:nth-child(6) a")).click();
    assertThat(driver.getTitle(), is("Carrello | DressMe Cloth collection"));
  }
  @Test
  public void testEliminaProdotto() {
    driver.get("http://localhost:8080/DressMe/loginPersonale.jsp");
    driver.manage().window().setSize(new Dimension(1054, 807));
    driver.findElement(By.id("username")).click();
    driver.findElement(By.id("username")).sendKeys("prodotti@gmail.com");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("AdminAdmin");
    driver.findElement(By.id("login-submit")).click();
    driver.findElement(By.cssSelector("tr:nth-child(4) a:nth-child(2)")).click();
    driver.findElement(By.cssSelector("p")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("p"));
      assert(elements.size() > 0);
    }
  }
}
