package seleniumTestSuite;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class ModificaProdottoTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
		 js = (JavascriptExecutor) driver;
			vars = new HashMap<String, Object>();
			System.setProperty("webdriver.chrome.driver",
					"C:\\Users\\franc\\Desktop\\Selenium\\chromedriver_win32\\chromedriver.exe");
			driver = new ChromeDriver();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void modificaProdotto222() {
    driver.get("http://localhost:8080/DressMe/loginPersonale.jsp");
    driver.manage().window().setSize(new Dimension(784, 816));
    driver.findElement(By.id("username")).click();
    driver.findElement(By.id("username")).sendKeys("prodotti@gmail.com");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("AdminAdmin");
    driver.findElement(By.id("login-submit")).click();
    driver.findElement(By.cssSelector("tr:nth-child(4) a:nth-child(1)")).click();
    driver.findElement(By.id("prezzo")).click();
    driver.findElement(By.id("prezzo")).sendKeys("0");
    driver.findElement(By.id("update")).click();
    assertThat(driver.switchTo().alert().getText(), is("Il prezzo che hai inserito non è valido"));
  }
  @Test
  public void modificaProdotto223() {
    driver.get("http://localhost:8080/DressMe/loginPersonale.jsp");
    driver.manage().window().setSize(new Dimension(784, 816));
    driver.findElement(By.id("username")).click();
    driver.findElement(By.id("username")).sendKeys("prodotti@gmail.com");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("AdminAdmin");
    driver.findElement(By.id("login-submit")).click();
    driver.findElement(By.cssSelector("tr:nth-child(4) a:nth-child(1)")).click();
    driver.findElement(By.id("idcategoria")).click();
    {
      WebElement dropdown = driver.findElement(By.id("idcategoria"));
      dropdown.findElement(By.xpath("//option[. = 'Donna']")).click();
    }
    driver.findElement(By.id("quantitaVestito")).click();
    driver.findElement(By.id("quantitaVestito")).sendKeys("10");
    driver.findElement(By.id("titolo")).click();
    driver.findElement(By.id("titolo")).sendKeys("Maglia rossa");
    driver.findElement(By.id("descrizione")).click();
    driver.findElement(By.id("descrizione")).sendKeys("Maglia rossa in cotone");
    driver.findElement(By.id("prezzo")).click();
    driver.findElement(By.id("prezzo")).click();
    {
      WebElement element = driver.findElement(By.id("prezzo"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("prezzo")).sendKeys("20");
    driver.findElement(By.id("update")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("p"));
      assert(elements.size() > 0);
    }
  }
}
