package seleniumTestSuite;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class ModificaPasswordTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
		 js = (JavascriptExecutor) driver;
			vars = new HashMap<String, Object>();
			System.setProperty("webdriver.chrome.driver",
					"C:\\Users\\franc\\Desktop\\Selenium\\chromedriver_win32\\chromedriver.exe");
			driver = new ChromeDriver();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void modificaPassword131() {
    driver.get("http://localhost:8080/DressMe/");
    driver.manage().window().setSize(new Dimension(803, 816));
    driver.findElement(By.linkText("Login")).click();
    driver.findElement(By.id("login-username")).click();
    driver.findElement(By.id("login-username")).sendKeys("ciromertens@gmail.com");
    driver.findElement(By.id("login-password")).click();
    driver.findElement(By.id("login-password")).sendKeys("ABCD1234");
    driver.findElement(By.id("login-submit")).click();
    driver.findElement(By.linkText("Account")).click();
    driver.findElement(By.cssSelector("b")).click();
    driver.findElement(By.id("Signin-submit")).click();
  }
  @Test
  public void modificaPassword132() {
    driver.get("http://localhost:8080/DressMe/");
    driver.manage().window().setSize(new Dimension(803, 816));
    driver.findElement(By.linkText("Login")).click();
    driver.findElement(By.id("login-username")).click();
    driver.findElement(By.id("login-username")).sendKeys("ciromertens@gmail.com");
    driver.findElement(By.id("login-password")).click();
    driver.findElement(By.id("login-password")).sendKeys("ABCD1234");
    driver.findElement(By.id("login-submit")).click();
    driver.findElement(By.linkText("Account")).click();
    driver.findElement(By.linkText("Vuoi cambiare la password? Clicca qua")).click();
    driver.findElement(By.id("vecchiaPassword")).click();
    driver.findElement(By.id("vecchiaPassword")).sendKeys("EFGH5678");
    driver.findElement(By.id("nuovaPassword")).click();
    driver.findElement(By.id("nuovaPassword")).sendKeys("EFGH5678");
    driver.findElement(By.id("confermaPassword")).click();
    driver.findElement(By.id("confermaPassword")).sendKeys("EFGH5678");
    driver.findElement(By.id("Signin-submit")).click();
    {
      List<WebElement> elements = driver.findElements(By.id("signin-message"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void modificaPassword133() {
    driver.get("http://localhost:8080/DressMe/");
    driver.manage().window().setSize(new Dimension(806, 816));
    driver.findElement(By.linkText("Login")).click();
    driver.findElement(By.id("login-username")).click();
    driver.findElement(By.id("login-username")).sendKeys("ciromertens@gmail.com");
    driver.findElement(By.id("login-password")).click();
    driver.findElement(By.id("login-password")).sendKeys("ABCD1234");
    driver.findElement(By.id("login-submit")).click();
    driver.findElement(By.linkText("Account")).click();
    driver.findElement(By.cssSelector("b")).click();
    driver.findElement(By.id("vecchiaPassword")).click();
    driver.findElement(By.id("vecchiaPassword")).sendKeys("ABCD1234");
    driver.findElement(By.id("nuovaPassword")).click();
    driver.findElement(By.id("nuovaPassword")).sendKeys("5678");
    driver.findElement(By.id("confermaPassword")).click();
    driver.findElement(By.id("confermaPassword")).sendKeys("5678");
    driver.findElement(By.id("Signin-submit")).click();
    {
      WebElement element = driver.findElement(By.id("Signin-submit"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      List<WebElement> elements = driver.findElements(By.id("signin-message"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void modificaPassword134() {
    driver.get("http://localhost:8080/DressMe/");
    driver.manage().window().setSize(new Dimension(809, 816));
    driver.findElement(By.linkText("Login")).click();
    driver.findElement(By.id("login-username")).click();
    driver.findElement(By.id("login-username")).sendKeys("ciromertens@gmail.com");
    driver.findElement(By.id("login-password")).click();
    driver.findElement(By.id("login-password")).sendKeys("ABCD1234");
    driver.findElement(By.id("login-submit")).click();
    driver.findElement(By.linkText("Account")).click();
    driver.findElement(By.linkText("Vuoi cambiare la password? Clicca qua")).click();
    driver.findElement(By.id("vecchiaPassword")).click();
    driver.findElement(By.id("vecchiaPassword")).sendKeys("ABCD1234");
    driver.findElement(By.id("nuovaPassword")).click();
    driver.findElement(By.id("nuovaPassword")).sendKeys("EFGH5678");
    driver.findElement(By.id("confermaPassword")).click();
    driver.findElement(By.id("confermaPassword")).sendKeys("ABCD1234");
    driver.findElement(By.id("Signin-submit")).click();
    {
      List<WebElement> elements = driver.findElements(By.id("signin-message"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void modificaPassword135() {
    driver.get("http://localhost:8080/DressMe/");
    driver.manage().window().setSize(new Dimension(809, 816));
    driver.findElement(By.linkText("Login")).click();
    driver.findElement(By.id("login-username")).click();
    driver.findElement(By.id("login-username")).sendKeys("ciromertens@gmail.com");
    driver.findElement(By.id("login-password")).click();
    driver.findElement(By.id("login-password")).sendKeys("ABCD1234");
    driver.findElement(By.id("login-submit")).click();
    driver.findElement(By.linkText("Account")).click();
    driver.findElement(By.cssSelector("b")).click();
    driver.findElement(By.id("vecchiaPassword")).click();
    driver.findElement(By.id("vecchiaPassword")).sendKeys("ABCD1234");
    driver.findElement(By.id("nuovaPassword")).click();
    driver.findElement(By.id("nuovaPassword")).sendKeys("EFGH5678");
    driver.findElement(By.id("confermaPassword")).click();
    driver.findElement(By.id("confermaPassword")).sendKeys("EFGH5678");
    driver.findElement(By.id("Signin-submit")).click();
    assertThat(driver.getTitle(), is("Account | DressMe Cloth collection"));
  }
}
