package seleniumTestSuite;


// Generated by Selenium IDE
//Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class TestAcquisto extends Thread  {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  
  @Before
  public void setUp()  {
		 js = (JavascriptExecutor) driver;
			vars = new HashMap<String, Object>();
			System.setProperty("webdriver.chrome.driver",
					"C:\\Users\\franc\\Desktop\\Selenium\\chromedriver_win32\\chromedriver.exe");
			driver = new ChromeDriver();

	  	driver.get("http://localhost:8080/DressMe/");
	    driver.manage().window().setSize(new Dimension(784, 816));
	    driver.findElement(By.linkText("Login")).click();
	    driver.findElement(By.id("login-username")).click();
	    driver.findElement(By.id("login-username")).sendKeys("nessuno@gmail.com");
	    driver.findElement(By.id("login-password")).click();
	    driver.findElement(By.id("login-password")).sendKeys("AdminAdmin");
	    driver.findElement(By.id("login-submit")).click();
  }
  
  @After
  public void tearDown() {
    driver.quit();
  }
  
  @Test
  public void acquistoSuccess() throws InterruptedException {
    driver.get("http://localhost:8080/DressMe/CarrelloFineControl");
    driver.manage().window().setSize(new Dimension(792, 816));
    driver.findElement(By.cssSelector("div:nth-child(15) b")).click();
    Thread.sleep(1000);
    driver.findElement(By.id("nomeS")).click();
    driver.findElement(By.id("nomeS")).sendKeys("Ciro");
    Thread.sleep(1000);
    driver.findElement(By.id("cognomeS")).click();
    driver.findElement(By.id("cognomeS")).sendKeys("Mertens");
    Thread.sleep(1000);
    driver.findElement(By.id("indirizzoS")).click();
    driver.findElement(By.id("indirizzoS")).sendKeys("Via San Ciro 30");
    Thread.sleep(1000);
    driver.findElement(By.id("capS")).click();
    driver.findElement(By.id("capS")).sendKeys("80100");
    Thread.sleep(1000);
    driver.findElement(By.id("comuneS")).click();
    driver.findElement(By.id("comuneS")).sendKeys("Roccarainola");
    Thread.sleep(1000);
    driver.findElement(By.id("provinciaS")).click();
    driver.findElement(By.id("provinciaS")).sendKeys("Napoli");
    Thread.sleep(1000);
    driver.findElement(By.id("login-submit")).click();
    driver.findElement(By.id("cod")).click();
    driver.findElement(By.id("cod")).sendKeys("1234 5678 1234 1234");
    Thread.sleep(1000);
    driver.findElement(By.id("nome")).click();
    driver.findElement(By.id("nome")).sendKeys("Ciro");
    Thread.sleep(1000);
    driver.findElement(By.id("scadenza")).click();
    driver.findElement(By.id("scadenza")).click();
    {
      WebElement element = driver.findElement(By.id("scadenza"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("scadenza")).sendKeys("04-2022");
    Thread.sleep(1000);
    driver.findElement(By.id("cvc")).click();
    driver.findElement(By.id("cvc")).sendKeys("123");
    driver.findElement(By.cssSelector(".buy")).click();
    assertThat(driver.getTitle(), is("Account | DressMe Cloth collection"));
    Thread.sleep(1000);
  }
  
  
  @Test
  public void acquistoCaperror() throws InterruptedException {
    driver.get("http://localhost:8080/DressMe/CarrelloFineControl");
    driver.manage().window().setSize(new Dimension(784, 816));
    driver.findElement(By.linkText("Procedi all\'ordine")).click();
    driver.findElement(By.id("nomeS")).click();
    driver.findElement(By.id("nomeS")).sendKeys("Ciro");
    Thread.sleep(1000);
    driver.findElement(By.id("cognomeS")).click();
    driver.findElement(By.id("cognomeS")).sendKeys("Mertens");
    Thread.sleep(1000);
    driver.findElement(By.id("indirizzoS")).click();
    driver.findElement(By.id("indirizzoS")).sendKeys("Via San Ciro 30");
    Thread.sleep(1000);
    driver.findElement(By.id("capS")).click();
    driver.findElement(By.id("capS")).sendKeys("80");
    Thread.sleep(1000);
    driver.findElement(By.id("comuneS")).click();
    driver.findElement(By.id("comuneS")).sendKeys("Roccarainola");
    Thread.sleep(1000);
    driver.findElement(By.id("provinciaS")).click();
    driver.findElement(By.id("provinciaS")).sendKeys("Napoli");
    Thread.sleep(1000);
    driver.findElement(By.id("login-submit")).click();
    {
      List<WebElement> elements = driver.findElements(By.id("spedizione-message"));
      assert(elements.size() > 0);
    }
  }
  
  @Test
  public void acquistoCodiceCartaerror() throws InterruptedException {
    driver.get("http://localhost:8080/DressMe/CarrelloFineControl");
    driver.manage().window().setSize(new Dimension(784, 816));
    Thread.sleep(1000);
    driver.findElement(By.cssSelector("div:nth-child(15) b")).click();
    driver.findElement(By.id("nomeS")).click();
    driver.findElement(By.id("nomeS")).sendKeys("Ciro");
    Thread.sleep(1000);
    driver.findElement(By.id("cognomeS")).click();
    driver.findElement(By.id("cognomeS")).sendKeys("Mertens");
    Thread.sleep(1000);
    driver.findElement(By.id("indirizzoS")).click();
    driver.findElement(By.id("indirizzoS")).sendKeys("Via San Ciro 30");
    Thread.sleep(1000);
    driver.findElement(By.id("capS")).click();
    driver.findElement(By.id("capS")).sendKeys("80100");
    Thread.sleep(1000);
    driver.findElement(By.id("comuneS")).click();
    driver.findElement(By.id("comuneS")).sendKeys("Roccarainola");
    Thread.sleep(1000);
    driver.findElement(By.id("provinciaS")).click();
    driver.findElement(By.id("provinciaS")).sendKeys("Napoli");
    Thread.sleep(1000);
    driver.findElement(By.id("login-submit")).click();
    driver.findElement(By.id("cod")).click();
    driver.findElement(By.id("cod")).sendKeys("1234 5678 910");
    Thread.sleep(1000);
    driver.findElement(By.id("nome")).click();
    driver.findElement(By.id("nome")).sendKeys("Ciro");
    Thread.sleep(1000);
    driver.findElement(By.id("scadenza")).click();
    driver.findElement(By.id("scadenza")).sendKeys("04-2022");
    Thread.sleep(1000);
    driver.findElement(By.id("cvc")).click();
    driver.findElement(By.id("cvc")).sendKeys("123");
    Thread.sleep(1000);
    driver.findElement(By.cssSelector(".buy")).click();
    {
      List<WebElement> elements = driver.findElements(By.id("pagamento-message"));
      assert(elements.size() > 0);
    }
    Thread.sleep(1000);
  }
  @Test
  public void acquistoCvcerror() throws InterruptedException {
    driver.get("http://localhost:8080/DressMe/CarrelloFineControl");
    driver.manage().window().setSize(new Dimension(792, 816));
    driver.findElement(By.cssSelector("div:nth-child(15) b")).click();
    driver.findElement(By.id("nomeS")).click();
    driver.findElement(By.id("nomeS")).sendKeys("Ciro");
    Thread.sleep(1000);
    driver.findElement(By.id("cognomeS")).click();
    driver.findElement(By.id("cognomeS")).sendKeys("Mertens");
    Thread.sleep(1000);
    driver.findElement(By.id("indirizzoS")).click();
    driver.findElement(By.id("indirizzoS")).sendKeys("Via San Ciro 30");
    Thread.sleep(1000);
    driver.findElement(By.id("capS")).click();
    driver.findElement(By.id("capS")).sendKeys("80100");
    Thread.sleep(1000);
    driver.findElement(By.id("comuneS")).click();
    driver.findElement(By.id("comuneS")).sendKeys("Roccarainola");
    Thread.sleep(1000);
    driver.findElement(By.id("provinciaS")).click();
    driver.findElement(By.id("provinciaS")).sendKeys("Napoli");
    Thread.sleep(1000);
    driver.findElement(By.id("login-submit")).click();
    driver.findElement(By.id("cod")).click();
    driver.findElement(By.id("cod")).sendKeys("1234 5678 1234 1234");
    Thread.sleep(1000);
    driver.findElement(By.id("nome")).click();
    driver.findElement(By.id("nome")).sendKeys("Ciro Mertens");
    Thread.sleep(1000);
    driver.findElement(By.id("scadenza")).click();
    driver.findElement(By.id("scadenza")).sendKeys("04-2022");
    Thread.sleep(1000);
    driver.findElement(By.id("cvc")).click();
    driver.findElement(By.id("cvc")).sendKeys("12");
    Thread.sleep(1000);
    driver.findElement(By.cssSelector(".buy")).click();
    {
      List<WebElement> elements = driver.findElements(By.id("pagamento-message"));
      assert(elements.size() > 0);
    }
    Thread.sleep(1000);
  }
  @Test
  public void acquistoDataCartaerror() throws InterruptedException {
    driver.get("http://localhost:8080/DressMe/CarrelloFineControl");
    driver.manage().window().setSize(new Dimension(788, 816));
    driver.findElement(By.linkText("Procedi all\'ordine")).click();
    driver.findElement(By.id("nomeS")).click();
    driver.findElement(By.id("nomeS")).sendKeys("Ciro");
    Thread.sleep(1000);
    driver.findElement(By.id("cognomeS")).click();
    driver.findElement(By.id("cognomeS")).sendKeys("Mertens");
    Thread.sleep(1000);
    driver.findElement(By.id("indirizzoS")).click();
    driver.findElement(By.id("indirizzoS")).sendKeys("Via San Ciro 30");
    Thread.sleep(1000);
    driver.findElement(By.id("capS")).click();
    driver.findElement(By.id("capS")).sendKeys("80100");
    Thread.sleep(1000);
    driver.findElement(By.id("comuneS")).click();
    driver.findElement(By.id("comuneS")).sendKeys("Roccarainola");
    Thread.sleep(1000);
    driver.findElement(By.id("provinciaS")).click();
    driver.findElement(By.id("provinciaS")).sendKeys("Napoli");
    Thread.sleep(1000);
    driver.findElement(By.id("login-submit")).click();
    driver.findElement(By.id("cod")).click();
    driver.findElement(By.id("cod")).sendKeys("1234 5678 9191 1234");
    Thread.sleep(1000);
    driver.findElement(By.id("nome")).click();
    driver.findElement(By.id("nome")).sendKeys("Ciro");
    Thread.sleep(1000);
    driver.findElement(By.id("scadenza")).click();
    driver.findElement(By.id("scadenza")).sendKeys("04-3");
    Thread.sleep(1000);
    driver.findElement(By.id("cvc")).click();
    driver.findElement(By.id("cvc")).sendKeys("123");
    Thread.sleep(1000);
    driver.findElement(By.cssSelector(".buy")).click();
    {
      List<WebElement> elements = driver.findElements(By.id("pagamento-message"));
      assert(elements.size() > 0);
    }
    Thread.sleep(1000);
  }
  @Test
  public void acquistoPagNull() throws InterruptedException {
    driver.get("http://localhost:8080/DressMe/CarrelloFineControl");
    driver.manage().window().setSize(new Dimension(784, 816));
    driver.findElement(By.cssSelector("div:nth-child(15) b")).click();
    driver.findElement(By.id("nomeS")).click();
    driver.findElement(By.id("nomeS")).sendKeys("Ciro");
    Thread.sleep(1000);
    driver.findElement(By.id("cognomeS")).click();
    driver.findElement(By.id("cognomeS")).sendKeys("Mertens");
    Thread.sleep(1000);
    driver.findElement(By.id("indirizzoS")).click();
    driver.findElement(By.id("indirizzoS")).sendKeys("Via San Ciro 30");
    Thread.sleep(1000);
    driver.findElement(By.id("capS")).click();
    driver.findElement(By.id("capS")).sendKeys("80100");
    Thread.sleep(1000);
    driver.findElement(By.id("comuneS")).click();
    driver.findElement(By.id("comuneS")).sendKeys("Roccarainola");
    Thread.sleep(1000);
    driver.findElement(By.id("provinciaS")).click();
    driver.findElement(By.id("provinciaS")).sendKeys("Napoli");
    Thread.sleep(1000);
    driver.findElement(By.id("login-submit")).click();
    driver.findElement(By.cssSelector(".buy")).click();
    Thread.sleep(1000);
  }
  @Test
  public void acquistoSpedNull() throws InterruptedException {
    driver.get("http://localhost:8080/DressMe/CarrelloFineControl");
    driver.manage().window().setSize(new Dimension(786, 816));
    driver.findElement(By.cssSelector("div:nth-child(15) b")).click();
    driver.findElement(By.id("nomeS")).click();
    Thread.sleep(1000);
    driver.findElement(By.id("cognomeS")).click();
    Thread.sleep(1000);
    driver.findElement(By.id("indirizzoS")).click();
    Thread.sleep(1000);
    driver.findElement(By.id("capS")).click();
    Thread.sleep(1000);
    driver.findElement(By.id("comuneS")).click();
    Thread.sleep(1000);
    driver.findElement(By.id("provinciaS")).click();
    Thread.sleep(1000);
    driver.findElement(By.id("login-submit")).click();
    Thread.sleep(1000);
  }
  @Test
  public void pagamentoBugData() throws InterruptedException {
    driver.get("http://localhost:8080/DressMe/CarrelloFineControl");
    driver.manage().window().setSize(new Dimension(789, 816));
    driver.findElement(By.cssSelector("div:nth-child(15) b")).click();
    driver.findElement(By.id("nomeS")).click();
    driver.findElement(By.id("nomeS")).sendKeys("Ciro ");
    Thread.sleep(1000);
    driver.findElement(By.id("cognomeS")).click();
    driver.findElement(By.id("cognomeS")).sendKeys("Mertens");
    Thread.sleep(1000);
    driver.findElement(By.id("indirizzoS")).click();
    driver.findElement(By.id("indirizzoS")).sendKeys("Via San Ciro 30");
    Thread.sleep(1000);
    driver.findElement(By.id("capS")).click();
    driver.findElement(By.id("capS")).sendKeys("80100");
    Thread.sleep(1000);
    driver.findElement(By.id("comuneS")).click();
    driver.findElement(By.id("comuneS")).sendKeys("Roccarainola");
    Thread.sleep(1000);
    driver.findElement(By.cssSelector(".user-box:nth-child(5)")).click();
    driver.findElement(By.id("provinciaS")).click();
    driver.findElement(By.id("provinciaS")).sendKeys("Napoli");
    Thread.sleep(1000);
    driver.findElement(By.id("login-submit")).click();
    driver.findElement(By.id("cod")).click();
    driver.findElement(By.id("cod")).click();
    Thread.sleep(1000);
    {
      WebElement element = driver.findElement(By.id("cod"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("cod")).sendKeys("1234 5678 1234 1234");
    driver.findElement(By.id("nome")).click();
    driver.findElement(By.id("nome")).sendKeys("Ciro Mertens");
    Thread.sleep(1000);
    driver.findElement(By.id("scadenza")).click();
    driver.findElement(By.id("scadenza")).sendKeys("01-1900");
    Thread.sleep(1000);
    driver.findElement(By.id("cvc")).click();
    driver.findElement(By.id("cvc")).sendKeys("123");
    Thread.sleep(1000);
     driver.findElement(By.cssSelector(".buy")).click();
     assertThat(driver.getTitle(), is("Account | DressMe Cloth collection"));
    Thread.sleep(1000);
  }
}
